package com.junkfood.seal.util

// Modified by the Trawl project on 2026-08-25 (GPL-3.0 section 5(a)).
// Changes: exported metadata is stamped Trawl.

import androidx.annotation.CheckResult
import com.junkfood.seal.database.objects.SavedCommentSet
import java.io.File
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json

/**
 * Export helpers for the "Comment Download" tool's saved comment sets. Mirrors the exact
 * structure/conventions of [VideoInfoExportUtil] (same docs directory, same TXT/JSON split,
 * same file-naming pattern) so both tools feel like the same feature family.
 */
object CommentExportUtil {

    private val prettyJson = Json {
        prettyPrint = true
        encodeDefaults = true
    }

    private fun safeFileName(title: String): String =
        title.ifBlank { "comments" }.replace(Regex("""[<>:"/\\|?*]"""), "_").take(100)

    @CheckResult
    fun exportAsTxt(commentSet: SavedCommentSet): Result<String> = runCatching {
        val docsDir = FileUtil.getDocsDirectory()
        val file = File(docsDir, "${safeFileName(commentSet.videoTitle)} - Comments.txt")
        val content = buildString {
            appendLine("═══════════════════════════════════════")
            appendLine("  VIDEO COMMENTS")
            appendLine("═══════════════════════════════════════")
            appendLine()
            appendLine("Video: ${commentSet.videoTitle}")
            if (commentSet.uploader.isNotBlank()) appendLine("Channel: ${commentSet.uploader}")
            if (commentSet.videoUrl.isNotBlank()) appendLine("URL: ${commentSet.videoUrl}")
            appendLine("Total comments: ${commentSet.commentCount}")
            appendLine()
            appendLine("───────────────────────────────────────")
            appendLine()
            commentSet.comments.forEach { comment ->
                val indent = if (comment.isReply) "    ↳ " else ""
                appendLine("$indent${comment.author}${if (comment.authorIsUploader) " (Creator)" else ""}")
                comment.timestamp?.let {
                    appendLine("$indent${formatTimestamp(it)}" + comment.likeCount?.let { likes -> "  •  $likes likes" }.orEmpty())
                }
                appendLine("$indent${comment.text}")
                appendLine()
            }
            appendLine("═══════════════════════════════════════")
            appendLine("  Generated by Trawl")
            appendLine("═══════════════════════════════════════")
        }
        FileUtil.writeContentToFile(content, file)
        file.absolutePath
    }

    @CheckResult
    fun exportAsJson(commentSet: SavedCommentSet): Result<String> = runCatching {
        val docsDir = FileUtil.getDocsDirectory()
        val file = File(docsDir, "${safeFileName(commentSet.videoTitle)} - Comments.json")
        val exportModel = CommentSetJsonExport(
            videoTitle = commentSet.videoTitle,
            uploader = commentSet.uploader,
            videoUrl = commentSet.videoUrl,
            commentCount = commentSet.commentCount,
            comments = commentSet.comments,
        )
        val content = prettyJson.encodeToString(exportModel)
        FileUtil.writeContentToFile(content, file)
        file.absolutePath
    }

    /** Plain, comma-separated CSV — handy for opening in a spreadsheet. */
    @CheckResult
    fun exportAsCsv(commentSet: SavedCommentSet): Result<String> = runCatching {
        val docsDir = FileUtil.getDocsDirectory()
        val file = File(docsDir, "${safeFileName(commentSet.videoTitle)} - Comments.csv")
        val content = buildString {
            appendLine("author,is_reply,likes,timestamp,text")
            commentSet.comments.forEach { comment ->
                appendLine(
                    listOf(
                        csvEscape(comment.author),
                        comment.isReply.toString(),
                        (comment.likeCount ?: 0).toString(),
                        comment.timestamp?.let { formatTimestamp(it) }.orEmpty(),
                        csvEscape(comment.text),
                    ).joinToString(","),
                )
            }
        }
        FileUtil.writeContentToFile(content, file)
        file.absolutePath
    }

    private fun csvEscape(value: String): String =
        "\"${value.replace("\"", "\"\"").replace("\n", " ")}\""

    private fun formatTimestamp(epochSeconds: Long): String =
        runCatching {
            SimpleDateFormat("yyyy-MM-dd HH:mm", Locale.getDefault())
                .format(Date(epochSeconds * 1000))
        }.getOrDefault("")

    @kotlinx.serialization.Serializable
    private data class CommentSetJsonExport(
        val videoTitle: String,
        val uploader: String,
        val videoUrl: String,
        val commentCount: Int,
        val comments: List<Comment>,
    )
}
